### PR TITLE
added; images responsive

### PR DESCRIPTION
**Pull request by Dev-AkshatGupta**
Please review it . There was nothing much in it to change as I was its my default styling with Images. Thank you
live-https://loving-shockley-e39c7a.netlify.app

### CODE REVIEW

**Comment by vrinda-mahajan** [comment]
Looks good!👍

**Review by nayyyhaa — APPROVED** [review]
Looks good to me 👍

**Comment by Dev-AkshatGupta** [comment]
> Looks good to me 👍

Thanks for reviewing :)

**Comment by Dev-AkshatGupta** [comment]
> Looks good!👍

Thanks for reviewing :)

**Pull request merged**
