### PR TITLE
added one more list component and also a slider component

### PR DESCRIPTION
**Pull request by Dev-AkshatGupta**
Hello everyone please review this code.
I have added a new list component and also a slider component is added
 Thanks a lot

### CODE REVIEW

**Review by vrinda-mahajan — APPROVED** [review]
The code looks good. It is generally a good practice to add an extra line at the end of each file.

**Review by keshavkumar-in — APPROVED** [review]
Code looks good to me but I am not able to under the UI what you are trying to achieve. For me it looks like this. So I am not clear about it.
akshat

**Comment by Dev-AkshatGupta** [comment]
> Code looks good to me but I am not able to under the UI what you are trying to achieve. For me it looks like this. So I am not clear about it. akshat

thanks for reviewing it . Its just my component I will document them on different website It will make sense there all together.

**Comment by Dev-AkshatGupta** [comment]
> The code looks good. It is generally a good practice to add an extra line at the end of each file.

Thanks a lot for reviewing it Vrinda . Yeah its just for showing purpose it won't have any html afterwards

**Pull request merged**
