### PR TITLE
added :nav and modal and toast

### PR DESCRIPTION
**Pull request by Dev-AkshatGupta**
Hey everyone please review it Thanks alott

### CODE REVIEW

**Review by foolhardy21 — APPROVED** [review]
LGTM. one thing, if the justify-content in toast is intentional then its okay. otherwise you can make it space-between to take up the whole space.

**Comment by MayankKumar10** [comment]
Add some padding in the model and hamburger menu div on hover

**Review by MayankKumar10 — COMMENTED** [review]
.

**Review by MayankKumar10 — APPROVED** [review]
Add some padding in the model and hamburger menu div on hover

**Comment by Dev-AkshatGupta** [comment]
> LGTM. one thing, if the justify-content in toast is intentional then its okay. otherwise you can make it space-between to take up the whole space.

Thanks for reviewing man Thats pretty much intentional

**Comment by Dev-AkshatGupta** [comment]
> Add some padding in the model and hamburger menu div on hover

But padding won't look good either it will mess with the layout on hovering

**Comment by MayankKumar10** [comment]
> 
It's just a suggestion, LGTM

**Comment by MayankKumar10** [comment]
> > But padding won't look good either it will mess with the layout on hovering
> 
> It's just a suggestion, everything else LGMT

**Pull request merged**
